package com.bjfdkj.singlecsl.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bjfdkj.singlecsl.db.bean.BookkeeperInfo;
import com.bjfdkj.singlecsl.db.bean.UserInfo;

import com.bjfdkj.singlecsl.db.BookkeeperInfoDao;
import com.bjfdkj.singlecsl.db.UserInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bookkeeperInfoDaoConfig;
    private final DaoConfig userInfoDaoConfig;

    private final BookkeeperInfoDao bookkeeperInfoDao;
    private final UserInfoDao userInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bookkeeperInfoDaoConfig = daoConfigMap.get(BookkeeperInfoDao.class).clone();
        bookkeeperInfoDaoConfig.initIdentityScope(type);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        bookkeeperInfoDao = new BookkeeperInfoDao(bookkeeperInfoDaoConfig, this);
        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);

        registerDao(BookkeeperInfo.class, bookkeeperInfoDao);
        registerDao(UserInfo.class, userInfoDao);
    }
    
    public void clear() {
        bookkeeperInfoDaoConfig.clearIdentityScope();
        userInfoDaoConfig.clearIdentityScope();
    }

    public BookkeeperInfoDao getBookkeeperInfoDao() {
        return bookkeeperInfoDao;
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

}
